In [1]:
import pandas as pd
import numpy as np

## Задание 0

Для всех  заданий будем использовать обезличенные транзакционные банковские данные. Для этого считайте в переменные **tr_mcc_codes, tr_types, transactions и gender_train** из одноимённых таблиц из папки [data](https://drive.google.com/drive/folders/1YAMe7MiTxA-RSSd8Ex2p-L0Dspe6Gs4L).

Для таблицы transactions используйте только первые n=1000000 строк. При чтении файлов обратите внимание на разделители внутри каждого из файлов - они могут различаться!

In [ ]:
https://drive.google.com/file/d/1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq/view?usp=sharing

In [21]:
!gdown 1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq

Downloading...
From (original): https://drive.google.com/uc?id=1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq
From (redirected): https://drive.google.com/uc?id=1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq&confirm=t&uuid=cc9e1847-095e-4610-9126-88f1a4f7ee76
To: /content/transactions.csv
100% 314M/314M [00:03<00:00, 83.7MB/s]

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/transactions.csv')

In [6]:
df.head()

   customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [7]:
new_df = df.groupby('customer_id').count().sort_values(by = 'tr_datetime', ascending=False)

In [8]:
new_df = new_df[new_df.tr_datetime>999]

In [9]:
new_df.index

Index([70780820, 45479973, 90796706,  6736634, 60151282, 35071735,  7999570,
       63233186, 25270793, 11701078,
       ...
       94756196, 79234235,  2470443, 42224807, 34767686, 24644305, 10011328,
       48101409, 68526161, 86397318],
      dtype='int64', name='customer_id', length=969)

In [10]:
df[df.customer_id.isin(new_df.index)]

         customer_id   tr_datetime  mcc_code  tr_type    amount   term_id
0           39026145    0 10:23:26      4814     1030  -2245.92       NaN
1           39026145    1 10:19:29      6011     7010  56147.89       NaN
2           39026145    1 10:20:56      4829     2330 -56147.89       NaN
3           39026145    1 10:39:54      5499     1010  -1392.47       NaN
4           39026145    2 15:33:42      5499     1010   -920.83       NaN
...              ...           ...       ...      ...       ...       ...
6811235     79686538  456 13:57:12      4814     1030  -4771.90    888908
6811236     79686538  456 18:04:00      6010     7031     22.46  10777890
6811237     79686538  456 19:07:10      4814     1030  -2268.37    888913
6811238     79686538  456 19:13:24      4814     1030  -1122.96    888906
6811239     79686538  456 21:29:51      6010     7071  22459.16    888986

[1954933 rows x 6 columns]

In [11]:
df[df.customer_id.isin(new_df.index)].to_csv ('transactions_short.csv')

In [12]:
df.customer_id

0          39026145
1          39026145
2          39026145
3          39026145
4          39026145
             ...
6849341    61870738
6849342    61870738
6849343    61870738
6849344    61870738
6849345    61870738
Name: customer_id, Length: 6849346, dtype: int64

In [23]:
!gdown --folder https://drive.google.com/drive/folders/1YAMe7MiTxA-RSSd8Ex2p-L0Dspe6Gs4L

Retrieving folder contents
Processing file 1eDmiNok26kSGPL48QKwaPG_ROO9yNItM accel.csv
Processing file 1hpO1lqvbdZ6K5zO66erNcYMr2rv_EFF1 apples_pears.csv
Processing file 1CW4RtZXiAdD6g51RmNMzToVQnAz8PRIj customers.zip
Processing file 1E4gvne4Nk85cgwEGpyfGkMX-TqshZekV data.txt
Processing file 1FG1fopcmvMZ7GBaBOqQipccSeFoMUvNT gender_train.csv
Processing file 1ULECgIh-34bO9ExraNwZUyBc1PHr1TuS omh.csv
Processing file 1pniJCHot77TlpYtndaMRi_qqYimzdBNJ predict_house_price_test_data.xlsx
Processing file 1q0xtwcDvh_igsBBB9K_QkwV2xOOM74OL predict_house_price_training_data.xlsx
Processing file 1IKfQNbkGADSFUdyPdVjQS-ucFhOiT6sM sms_spam.csv
Processing file 13G_yxcUABzMHjrAE9y-dui7lUY_KMbyB sp500.csv
Processing file 16MSmqLRcyq3iIAkO4U2i6xB1en4-ZlV2 tips.csv
Processing file 1B6DYzjLMiUvtW0NtQvL0PhGZ4iEEy5GcHA6YeyWSgcE tr_mcc_codes
Processing file 1ukKTW9ySGsIPiQGkxqQmUZ24azA0zPpzkEU_GOjYMzQ tr_mcc_codes
Processing file 10J8RzMIhoYHiad49r-oWNMAk-V5lo3OE tr_mcc_codes.csv
Processing file 1YZSTooLUZe6hVVCUgAYWDw6dQeJBMvX7O1RbF_WSy8E tr_types
Processing file 1EP3KrATWS1I_qYdpRhYnSDl-eoBiOBQc tr_types.csv
Processing file 1viqn9Y3kX2JjWyWAFupTouIwyIPxw1Ys transactions_short.csv
Processing file 1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq transactions.csv
Processing file 1_1YvZgUAgjKuRKPkkVnJlzQJy7rgkqBR voice.csv
Processing file 1j-DhO_XD5EqzOqVSR4Wz1kNzhLmpeTkZ women-clothing-accessories.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1eDmiNok26kSGPL48QKwaPG_ROO9yNItM
To: /content/Data/accel.csv
100% 114/114 [00:00<00:00, 598kB/s]
Downloading...
From: https://drive.google.com/uc?id=1hpO1lqvbdZ6K5zO66erNcYMr2rv_EFF1
To: /content/Data/apples_pears.csv
100% 43.6k/43.6k [00:00<00:00, 85.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1CW4RtZXiAdD6g51RmNMzToVQnAz8PRIj
To: /content/Data/customers.zip
100% 66.6k/66.6k [00:00<00:00, 116MB/s]
Downloading...
From: https://drive.google.com/uc?id=1E4gvne4Nk85cgwEGpyfGkMX-TqshZekV
To: /content/Data/data.txt
100% 27.0k/27.0k [00:00<00:00, 65.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FG1fopcmvMZ7GBaBOqQipccSeFoMUvNT
To: /content/Data/gender_train.csv
100% 99.9k/99.9k [00:00<00:00, 59.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ULECgIh-34bO9ExraNwZUyBc1PHr1TuS
To: /content/Data/omh.csv
100% 539/539 [00:00<00:00, 2.90MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pniJCHot77TlpYtndaMRi_qqYimzdBNJ
To: /content/Data/predict_house_price_test_data.xlsx
100% 563k/563k [00:00<00:00, 153MB/s]
Downloading...
From: https://drive.google.com/uc?id=1q0xtwcDvh_igsBBB9K_QkwV2xOOM74OL
To: /content/Data/predict_house_price_training_data.xlsx
100% 1.31M/1.31M [00:00<00:00, 106MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IKfQNbkGADSFUdyPdVjQS-ucFhOiT6sM
To: /content/Data/sms_spam.csv
100% 481k/481k [00:00<00:00, 122MB/s]
Downloading...
From: https://drive.google.com/uc?id=13G_yxcUABzMHjrAE9y-dui7lUY_KMbyB
To: /content/Data/sp500.csv
100% 83.6k/83.6k [00:00<00:00, 117MB/s]
Downloading...
From: https://drive.google.com/uc?id=16MSmqLRcyq3iIAkO4U2i6xB1en4-ZlV2
To: /content/Data/tips.csv
100% 6.54k/6.54k [00:00<00:00, 31.1MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1B6DYzjLMiUvtW0NtQvL0PhGZ4iEEy5GcHA6YeyWSgcE
From (redirected): https://docs.google.com/spreadsheets/d/1B6DYzjLMiUvtW0NtQvL0PhGZ4iEEy5GcHA6YeyWSgcE/export?format=xlsx
To: /content/Data/tr_mcc_codes
11.8kB [00:00, 14.2MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1ukKTW9ySGsIPiQGkxqQmUZ24azA0zPpzkEU_GOjYMzQ
From (redirected): https://docs.google.com/spreadsheets/d/1ukKTW9ySGsIPiQGkxqQmUZ24azA0zPpzkEU_GOjYMzQ/export?format=xlsx
To: /content/Data/tr_mcc_codes
10.8kB [00:00, 1.70MB/s]
Downloading...
From: https://drive.google.com/uc?id=10J8RzMIhoYHiad49r-oWNMAk-V5lo3OE
To: /content/Data/tr_mcc_codes.csv
100% 14.9k/14.9k [00:00<00:00, 53.8MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1YZSTooLUZe6hVVCUgAYWDw6dQeJBMvX7O1RbF_WSy8E
From (redirected): https://docs.google.com/spreadsheets/d/1YZSTooLUZe6hVVCUgAYWDw6dQeJBMvX7O1RbF_WSy8E/export?format=xlsx
To: /content/Data/tr_types
7.69kB [00:00, 38.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1EP3KrATWS1I_qYdpRhYnSDl-eoBiOBQc
To: /content/Data/tr_types.csv
100% 14.2k/14.2k [00:00<00:00, 51.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1viqn9Y3kX2JjWyWAFupTouIwyIPxw1Ys
To: /content/Data/transactions_short.csv
100% 104M/104M [00:00<00:00, 139MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq
From (redirected): https://drive.google.com/uc?id=1lEpoRKczv5EvZhff9O2I-0JkdHnbe_Mq&confirm=t&uuid=cdbe7c9f-6fda-4aeb-a09a-5dfe23c8c60e
To: /content/Data/transactions.csv
100% 314M/314M [00:02<00:00, 115MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_1YvZgUAgjKuRKPkkVnJlzQJy7rgkqBR
To: /content/Data/voice.csv
100% 1.07M/1.07M [00:00<00:00, 185MB/s]
Downloading...
From: https://drive.google.com/uc?id=1j-DhO_XD5EqzOqVSR4Wz1kNzhLmpeTkZ
To: /content/Data/women-clothing-accessories.csv
100% 21.8M/21.8M [00:00<00:00, 183MB/s]
Download completed

In [27]:
tr_mcc_codes = pd.read_csv('Data/tr_mcc_codes.csv', sep=';')
tr_types     = pd.read_csv('Data/tr_types.csv', sep=';')
gender_train = pd.read_csv('Data/gender_train.csv')

###  Описание данных
#### Таблица ```transactions.csv```
##### Описание
Таблица содержит историю транзакций клиентов банка за один год и три месяца.

##### Формат данных

```
customer_id,tr_datetime,mcc_code,tr_type,amount,term_id
111111,15 01:40:52,1111,1000,-5224,111111
111112,15 15:18:32,3333,2000,-100,11122233
...
```
##### Описание полей

 - ```customer_id``` — идентификатор клиента;
 - ```tr_datetime``` — день и время совершения транзакции (дни нумеруются с начала данных);
 - ```mcc_code``` — mcc-код транзакции;
 - ```tr_type``` — тип транзакции;
 - ```amount``` — сумма транзакции в условных единицах со знаком; ```+``` — начисление средств клиенту (приходная транзакция), ```-``` — списание средств (расходная транзакция);
 - ```term_id``` — идентификатор терминала;


#### Таблица ```gender_train.csv```

##### Описание
Данная таблица содержит информацию по полу для части клиентов, для которых он известен. Для остальных клиентов пол неизвестен.

##### Формат данных
```
customer_id,gender
111111,0
111112,1
...
```

##### Описание полей
 - ```customer_id``` — идентификатор клиента;
 - ```gender``` — пол клиента;

### Таблица ```tr_mcc_codes.csv```

##### Описание
Данная таблица содержит описание mcc-кодов транзакций.

##### Формат данных
```
mcc_code;mcc_description
1000;словесное описание mcc-кода 1000
2000;словесное описание mcc-кода 2000
...
```

##### Описание полей
 - ```mcc_code``` – mcc-код транзакции;
 - ```mcc_description``` — описание mcc-кода транзакции.

#### Таблица ```tr_types.csv```

##### Описание
Данная таблица содержит описание типов транзакций.

##### Формат данных
```
tr_type;tr_description
1000;словесное описание типа транзакции 1000
2000;словесное описание типа транзакции 2000
...
```

##### Описание полей
 - ```tr_type``` – тип транзакции;
 - ```tr_description``` — описание типа транзакции;


Задания 1-4 делаются без использования merge!

## Задание 1

1. Для столбца tr_type датафрейма transactions выберите произвольные 1000 строк с помощью метода sample
2. В полученной на предыдущем этапе подвыборке найдите долю транзакций (стобец tr_description в датасете tr_types), в которой содержится подстрока 'POS' или 'ATM'

In [31]:
transactions = pd.read_csv('transactions.csv', nrows=1000000)

sample = transactions['tr_type'].sample(1000, random_state=22)

descriptions = sample.map(tr_types.set_index('tr_type')['tr_description'])

share = descriptions.apply(lambda x: 'POS' in str(x) or 'ATM' in str(x)).mean()
share

np.float64(0.375)

## Задание 2

1. Для столбца tr_type датафрейма transactions посчитайте частоту встречаемости всех типов транзакций tr_type в transactions.
2. Выведите топ-10 транзакций по частоте встречаемости (вывести для них tr_description тоже).

In [32]:
counts = transactions['tr_type'].value_counts()

top10 = counts.head(10).reset_index()
top10.columns = ['tr_type', 'count']
top10['tr_description'] = top10['tr_type'].map(tr_types.set_index('tr_type')['tr_description'])
top10

   tr_type   count                                     tr_description
0     1010  231117                              Покупка. POS ТУ СБ РФ
1     2010  151166              Выдача наличных в АТМ Сбербанк России
2     7070  149006  Перевод на карту (с карты) через Мобильный бан...
3     1110  137658                             Покупка. POS ТУ Россия
4     1030  118975                     Оплата услуги. Банкоматы СБ РФ
5     2370   49830  Списание с карты на карту по операции <перевод...
6     7010   28972       Взнос наличных через АТМ (в своем тер.банке)
7     7030   26078  Перевод на карту (с карты) через АТМ (в предел...
8     7071   15781  Перевод на карту (с карты) через Мобильный бан...
9     1100   15476                                Покупка. ТУ  Россия

## Задание 3
1. В датафрейме transactions найдите клиента с максимальной суммой приходов на карту
2. В датафрейме transactions найдите клиента с максимальной суммой расходов по карте
3. Найдите модуль разницы для этих клиентов между суммой расходов и суммой приходов

In [34]:
income = transactions[transactions['amount'] > 0].groupby('customer_id')['amount'].sum()
max_income_client = income.idxmax()

expense = transactions[transactions['amount'] < 0].groupby('customer_id')['amount'].sum()
max_expense_client = expense.idxmin()

diff = abs(income[max_income_client] - expense[max_income_client])
diff2 = abs(income[max_expense_client] - expense[max_expense_client])

print(max_income_client, diff)
print(max_expense_client, diff2)

70780820 2498067091.6
70780820 2498067091.6

## Задание 4
1. Найдите среднее арифметическое и медиану по amount по всем типам транзакций из топ 10 из задания 2
1. Найдите среднее арифметическое и медиану по amount по всем типам транзакций для клиентов из задания 3

In [35]:
top10_types = top10['tr_type'].values

result1 = transactions[transactions['tr_type'].isin(top10_types)].groupby('tr_type')['amount'].agg(['mean', 'median'])
result1['tr_description'] = result1.index.map(tr_types.set_index('tr_type')['tr_description'])
print(result1)


clients = [max_income_client, max_expense_client]

result2 = transactions[transactions['customer_id'].isin(clients)].groupby('customer_id')['amount'].agg(['mean', 'median'])
print(result2)

                  mean     median  \
tr_type
1010     -19784.748640   -7411.52
1030      -5320.980222   -2245.92
1100     -44061.827262  -10188.26
1110     -32119.330371  -11207.57
2010    -136077.629325  -44918.32
2370    -205418.249032  -44918.32
7010     276391.789596  112295.79
7030      86104.332909   13951.52
7070      65569.831700   11319.42
7071      66806.826623    3593.47

                                            tr_description
tr_type
1010                                 Покупка. POS ТУ СБ РФ
1030                        Оплата услуги. Банкоматы СБ РФ
1100                                   Покупка. ТУ  Россия
1110                                Покупка. POS ТУ Россия
2010                 Выдача наличных в АТМ Сбербанк России
2370     Списание с карты на карту по операции <перевод...
7010          Взнос наличных через АТМ (в своем тер.банке)
7030     Перевод на карту (с карты) через АТМ (в предел...
7070     Перевод на карту (с карты) через Мобильный бан...
7071     Перевод на карту (с карты) через Мобильный бан...
                  mean   median
customer_id
70780820    -20.694946  8803.99

## Подготовка для заданий 5-8

*Из заданий 5-8 нужно выполнить минимум два любых*

Соедините transactions с всеми остальными таблицами (tr_mcc_codes, tr_types, gender_train). Причём с gender_train необходимо смёрджиться с помощью left join, а с оставшимися датафреймами - через inner.
После получения результата таблицы gender_train, tr_types, tr_mcc_codes можно удалить. В результате соединения датафреймов должно получиться 999584 строки.

In [36]:
transactions = pd.merge(transactions, gender_train, how='left')
transactions = pd.merge(transactions, tr_mcc_codes, how='inner')
transactions = pd.merge(transactions, tr_types, how='inner')
transactions.shape

(999584, 9)

## Задание 5

1. Определите модуль разницы между средними тратами женщин и мужчин (трата - отрицательное значение amount).
2. Определите модуль разницы между средними поступлениями у мужчин и женщин

Обратите внимание, что для вычисления модуля разности точных знаний о том,
какой класc относится к мужчинам, а какой - к женщинам, не требуется.

In [39]:
expenses = transactions[transactions['amount'] < 0].groupby('gender')['amount'].mean()
diff_expenses = abs(expenses.diff().iloc[-1])
print('Разница между средними тратами женщин и мужчин:', diff_expenses)

income = transactions[transactions['amount'] > 0].groupby('gender')['amount'].mean()
diff_income = abs(income.diff().iloc[-1])
print('разница между средними поступлениями у мужчин и женщин:', diff_income)

Разница между средними тратами женщин и мужчин: 32718.054920224655
разница между средними поступлениями у мужчин и женщин: 63366.57104801464

## Задание 6

1. По всем типам транзакций рассчитайте максимальную сумму прихода на карту (из строго положительных сумм по столбцу amount) отдельно для мужчин и женщин (назовите ее "max_income"). Оставьте по 10 типов транзакций для мужчин и для женщин, наименьших среди всех типов транзакций по полученным значениям "max_income".
2. Выделите среди них те типы транзакций, которые встречаются одновременно и у мужчин, и у женщин

In [43]:
max_income = transactions[transactions['amount'] > 0].groupby(['gender', 'tr_type'])['amount'].max().reset_index()
max_income.columns = ['gender', 'tr_type', 'max_income']

top10_men = max_income[max_income['gender'] == 0].nsmallest(10, 'max_income')
top10_women = max_income[max_income['gender'] == 1].nsmallest(10, 'max_income')

print(top10_men)
print(top10_women)

common = set(top10_men['tr_type']).intersection(set(top10_women['tr_type']))
common_descriptions = pd.Series(list(common)).map(tr_types.set_index('tr_type')['tr_description'])
print('Общие типы транзакций:\n', common_descriptions.values)

    gender  tr_type  max_income
10     0.0     4051     1122.96
12     0.0     4110     2245.92
13     0.0     4210     2245.92
9      0.0     2370     2335.75
11     0.0     4100     5041.86
36     0.0     7075     6737.75
6      0.0     2110    22459.16
0      0.0     1010    24839.83
5      0.0     2010    44918.32
7      0.0     2210    68315.82
    gender  tr_type  max_income
44     1.0     2020     2245.92
47     1.0     4110     2245.92
38     1.0     1010    28803.87
71     1.0     8100    64682.37
48     1.0     6000    79280.83
66     1.0     7041    87590.72
43     1.0     2010    89836.63
45     1.0     2110   112295.79
46     1.0     2370   113194.15
57     1.0     7015   121279.45
Общие типы транзакций:
 ['Списание с карты на карту по операции <перевода с карты на карту> через Мобильный банк (без комиссии)'
 'Плата за получение наличных в АТМ. Россия' 'Покупка. POS ТУ СБ РФ'
 'Выдача наличных в АТМ Сбербанк России' 'Наличные.   АТМ Россия']

## Задание 7

1. Найдите суммы затрат по каждой категории (mcc) для мужчин и для женщин.
2. Найдите топ 10 категорий с самыми большими относительными модулями разности в тратах для разных полов (в ответе должны присутствовать описания mcc кодов).

## Задание 8

1. Из поля tr_datetime выделите час tr_hour, в который произошла транзакция, как первые 2 цифры до ":". (\**)
2. Посчитайте количество транзакций с amount<0 в ночное время для мужчин и женщин. Ночное время - это примерно 00-06 часов.

In [49]:
!find /content -name "practice.ipynb"

/content/ML_GaN_Course-IDU_ITMO-2026/practice 00/practice.ipynb

In [51]:
git config --global user.email "victor.vyhuhol.777@gmail.com"
git config --global user.name "AnotherShittyJoke"

SyntaxError: invalid syntax (1804051280.py, line 1)

In [50]:
%cd "/content/ML_GaN_Course-IDU_ITMO-2026"
!git add .
!git commit -m "done tasks 1-6"
!git push

/content/ML_GaN_Course-IDU_ITMO-2026
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@4cfbb68c11e5.(none)')
fatal: could not read Username for 'https://github.com': No such device or address